# Generated by Django 2.0.5 on 2018-06-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180529_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2),
        ),
    ]
